services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algrotech-app
    ports:
      - "9352:9352"
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/.env
    environment:
      DB_DATABASE: algrotech
      DB_USERNAME: algrotechUser
      DB_PASSWORD: Agro@Db12Pass
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: algrotech-db
    environment:
      MYSQL_DATABASE: algrotech
      MYSQL_USER: algrotechUser
      MYSQL_PASSWORD: Agro@Db12Pass
      MYSQL_ROOT_PASSWORD: Agro@Db12Pass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: algrotech-redis
    ports:
      - "6379:6379"

volumes:
  dbdata: